import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import "./fontawesome-autoimport.js"; // Import autogenerated fontawesome imports

export const Fa = ({ class: className, ...props }) =>
  h(FontAwesomeIcon, {
    class: `focus:outline-0${className ? ` ${className}` : ""}`,
    ...props
  });

export default app =>
  // eslint-disable-next-line vue/component-definition-name-casing
  app.component("fa", Fa);
